name: SpigotBlankPlugin
main: com.meeku.tutorialPlugin.SpigotBlankPlugin
version: 1.0
api-version: 1.13
commands:
   kit:
      description: Your description
      usage: /<command>
      permission: yourplugin.yourcommandpermission 
   slideshow:
      description: Your description
      usage: /<command>
      permission: yourplugin.yourcommandpermission 